#Script to deploy on the render cloud platform

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{secrets.BMI}} #RENDER_API_KEY
          github-token: ${{secrets.ACC_API_KEY}} #This is the github token
          service-id: "srv-cioegrlph6elhbsdhga0?key=tbyVL7SpScg" #this is unique for each app
          retries: 20
          wait: 16000
          sleep: 30000

